api_version = "2025-04"

[[extensions]]
type = "theme_app_extension"
name = "RaffleBee Cart Banner"

[extensions.settings]
[[extensions.settings.blocks]]
type = "raffle_banner"
name = "Sweepstakes Banner"
target = "section_group://cart"

[[extensions.settings.blocks.settings]]
type = "text"
id = "banner_text"
label = "Banner Text"
default = "Add {amount} more for a chance to win {prize}!"

[[extensions.settings.blocks.settings]]
type = "color"
id = "banner_color"
label = "Banner Color"
default = "#1976d2"