# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "RaffleBee"
client_id = "206bca4f45097090e303515061f0414e"
application_url = "https://raffle-bee-production.up.railway.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,read_products"

[auth]
redirect_urls = [
  "https://raffle-bee-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""